### ISSUE TITLE
Question of Change Language 

### ISSUE THREAD

**Issue by JarrenPoh** [lyledean1/flutter_whisper.cpp#12]
Hi, I want to know how can I change the language mode?
And I also want to know can I use all these in release APP?

**Comment by jungsu0717** [comment]
> Hi, I want to know how can I change the language mode? And I also want to know can I use all these in release APP?

On a Mac (M1 silicon chip) building only in ARM64 arch.

Also, to set the language, you need to change Rust code. See the page below
[https://docs.rs/whisper-rs/latest/whisper_rs/struct.FullParams.html#method.set_language](url)

**Comment by lyledean1** [comment]
This is straight forward to add as a feature, you just need to pass the value through the FFI function from Dart -> Rust. I've added it in this PR https://github.com/lyledean1/flutter_whisper.cpp/pull/13 . See the updated code [here](https://github.com/lyledean1/flutter_whisper.cpp/blob/8848060ac8c385ee4336820bd6f2073c3f47c0e0/lib/audio_player.dart#L176). You also need to make sure you use the correct model, i.e tiny instead of tiny.en - see [OpenAIs docs](https://github.com/openai/whisper#available-models-and-languages)

In terms of running in production, release mode works for iOS, not for MacOS currently. Android still needs to be set up. I haven't ran this in production myself so can't give you any tips apart from the fact you will probably have a large binary size if you include the model file in your build.
